### ISSUE TITLE
Add load mat function

### ISSUE THREAD

**Issue by JCZuurmond** [Smn-Wltr/Onion_NMR#3]
We want to be able to load the mat file. Could somebody add a module `loader.py`, containing this function?

```python
def load_data(path_mat):
    onion_nmr = scipy.io.loadmat(path_mat)

    X = pd.DataFrame(onion_nmr['x'], columns=onion_nmr['ppm'].flatten())
    y = onion_nmr['onion'].flatten()
    return X, y
```

**Comment by rbschoop** [comment]
Hi, 
the loader will be done by Simon as was defined by our Project Manager Alex :)

**Comment by Smn-Wltr** [comment]
> We want to be able to load the mat file. Could somebody add a module `loader.py`, containing this function?
> 
> ```python
> def load_data(path_mat):
>     onion_nmr = scipy.io.loadmat(path_mat)
> 
>     X = pd.DataFrame(onion_nmr['x'], columns=onion_nmr['ppm'].flatten())
>     y = onion_nmr['onion'].flatten()
>     return X, y
> ```

Hi, loader is updated

**Comment by Smn-Wltr** [comment]
Updated
